/** Purely visual row-house scenery: fills out the residential district around the town core
 * so it reads as a dense, real settlement instead of a handful of named buildings on grass.
 * No interior, no interaction, no per-tick proximity checks — just a footprint on the map,
 * like background buildings in GTA. Positions were procedurally generated and filtered to land
 * + clearance from every other marker before being pasted in here.
 *
 * Full-town rebuild 2026-08-07 (item 52) — "start again," per direct feedback with reference
 * images of real 17th-century outlaw ports (Port Royal, Tortuga) and several hand-drawn fantasy
 * harbor-town maps: "organic, non-linear... waterfront centric... narrow thoroughfares... tightly
 * packed buildings," not a formal grid. Every prior iteration (see the item 39-50 history this
 * comment used to hold) kept the same fundamental shape — a hub-and-spoke square with row houses
 * lining a handful of streets — and kept failing the same feedback in different ways. This pass
 * replaced the shape instead: Tortuga's north coast is now a real horseshoe bay (see islands.ts),
 * and housing is a dense, organically-jittered scatter (not a grid, not row-lined spokes) packed
 * into the band between the coastal high street and the buildings behind it, all the way around
 * the crescent — 95 houses, generated by Poisson-disc-style rejection sampling (min 21 units
 * apart, min ~42 units from any building) and verified with a TypeScript script run directly
 * against the live data: every point inside TORTUGA_SHAPE, clear of every building/landmark/
 * marker, clear of every other house. The rural 'path' trails (West Point Shack, the Ruins, La
 * Ringot Fields, etc.) stay deliberately house-free — the same handful of standalone homesteads
 * near those as before covers the "sporadic elsewhere" half of the original ask, unchanged. */
export interface House {
  islandId: string;
  offset: { x: number; y: number }; // relative to island center, in world units
}

export const HOUSES: House[] = [
  // Dense organic house scatter wrapping the horseshoe bay, west headland to east headland —
  // Poisson-disc-style sampling rather than row-lined streets (95 houses).
  { islandId: 'tortuga_cove', offset: { x: -168, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -216, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 288, y: 0 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: 168, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 312, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: 24, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: -168, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: 360, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -192, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: -24, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -264 } },
  { islandId: 'tortuga_cove', offset: { x: 120, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -96, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: -72, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -168, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: 360, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 336, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 72, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: -96, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: -168, y: -288 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -264 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: -240, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: -264, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 0, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: -264, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: -24, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: 288, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: 168, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: 336, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: 120, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: 264, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -120, y: -264 } },
  { islandId: 'tortuga_cove', offset: { x: -96, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: -96, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: -72, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -288 } },
  { islandId: 'tortuga_cove', offset: { x: -288, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 384, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: -216, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: 24, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -120, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 48, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: -216, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -240 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -192, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -72, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: -144, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: -240, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -168, y: -120 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: 336, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: 120, y: -144 } },
  { islandId: 'tortuga_cove', offset: { x: 120, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 360, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -192, y: -72 } },
  { islandId: 'tortuga_cove', offset: { x: 336, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: 264, y: -96 } },
  { islandId: 'tortuga_cove', offset: { x: -24, y: -168 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: -240, y: -312 } },
  { islandId: 'tortuga_cove', offset: { x: 120, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: 168, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 240, y: -216 } },
  { islandId: 'tortuga_cove', offset: { x: -120, y: -288 } },
  // Sporadic houses: a single standalone homestead near each outlying location that's still on a
  // rural trail rather than a real street, instead of a second neighborhood — matches the existing
  // outpost pattern (West Point Shack, the Ruins, etc).
  { islandId: 'tortuga_cove', offset: { x: -360, y: 48 } }, // near West Point Shack
  { islandId: 'tortuga_cove', offset: { x: -480, y: 24 } }, // near El Fuerte Viejo (the Ruins)
  { islandId: 'tortuga_cove', offset: { x: 384, y: 168 } }, // near the Trapper's Camp
  { islandId: 'tortuga_cove', offset: { x: 240, y: 360 } }, // near the Old Landing Dock
  { islandId: 'tortuga_cove', offset: { x: 336, y: 216 } }, // near La Ringot Fields
  { islandId: 'tortuga_cove', offset: { x: 480, y: -48 } }, // near the High Woods
  { islandId: 'tortuga_cove', offset: { x: -120, y: 408 } }, // near the Forgotten Graves

  // Detached Row ("add everything" pass, 2026-08-13): nine houses evenly spaced along a straight
  // street south of the packed harbor core, per Blueprint Sheet 3 — a later, tidier addition to
  // the town rather than more of the cramped waterfront. Sits on the one long clear east-west
  // stretch of open ground between Bois Sombre and the coastline, checked clear of every existing
  // offset. See streets.ts for the row's own street plus its connector back to the harbor.
  { islandId: 'tortuga_cove', offset: { x: -264, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: -192, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: -120, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: -48, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: 0, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: 72, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: 192, y: 288 } },
  { islandId: 'tortuga_cove', offset: { x: 288, y: 288 } },

  // New Providence residential grid: generated the same way as Tortuga's original grid — candidate positions
  // along a residential avenue grid, filtered to inside the real island polygon and clear of
  // every building/fort/quest marker and every other house (see GAME_DESIGN.md for the script).
  { islandId: 'new_providence', offset: { x: -269, y: -278 } },
  // (-120,-104) dropped — too close to the rum resource node at (-140,-100), missed in the
  // original generation pass because resource nodes weren't in that script's marker list.
  { islandId: 'new_providence', offset: { x: -189, y: -278 } },
  { islandId: 'new_providence', offset: { x: -189, y: -202 } },
  { islandId: 'new_providence', offset: { x: -109, y: -278 } },
  { islandId: 'new_providence', offset: { x: -109, y: -202 } },
  { islandId: 'new_providence', offset: { x: -29, y: -278 } },
  { islandId: 'new_providence', offset: { x: -29, y: -202 } },
  { islandId: 'new_providence', offset: { x: 51, y: -278 } },
  { islandId: 'new_providence', offset: { x: 51, y: -202 } },
  { islandId: 'new_providence', offset: { x: 131, y: -278 } },
  { islandId: 'new_providence', offset: { x: 131, y: -202 } },
  { islandId: 'new_providence', offset: { x: -349, y: -132 } },
  { islandId: 'new_providence', offset: { x: -269, y: -132 } },
  { islandId: 'new_providence', offset: { x: -189, y: -132 } },
  { islandId: 'new_providence', offset: { x: -109, y: -132 } },
  { islandId: 'new_providence', offset: { x: -29, y: -132 } },
  { islandId: 'new_providence', offset: { x: 51, y: -132 } },
  { islandId: 'new_providence', offset: { x: 211, y: -132 } },
  { islandId: 'new_providence', offset: { x: -290, y: -72 } },
  { islandId: 'new_providence', offset: { x: -210, y: -68 } },
  { islandId: 'new_providence', offset: { x: -130, y: -68 } },
  { islandId: 'new_providence', offset: { x: -50, y: -68 } },
  { islandId: 'new_providence', offset: { x: 116, y: -63 } },
  { islandId: 'new_providence', offset: { x: 190, y: -68 } },
  { islandId: 'new_providence', offset: { x: 270, y: -68 } },
  { islandId: 'new_providence', offset: { x: 350, y: -68 } },
  { islandId: 'new_providence', offset: { x: -349, y: 8 } },
  { islandId: 'new_providence', offset: { x: -269, y: 8 } },
  { islandId: 'new_providence', offset: { x: -189, y: 8 } },
  { islandId: 'new_providence', offset: { x: -109, y: 8 } },
  { islandId: 'new_providence', offset: { x: 51, y: 74 } },
  { islandId: 'new_providence', offset: { x: 190, y: 2 } },
  { islandId: 'new_providence', offset: { x: 270, y: 2 } },
  { islandId: 'new_providence', offset: { x: 350, y: 2 } },
  { islandId: 'new_providence', offset: { x: -349, y: 78 } },
  { islandId: 'new_providence', offset: { x: -269, y: 78 } },
  { islandId: 'new_providence', offset: { x: -50, y: 72 } },
  { islandId: 'new_providence', offset: { x: -29, y: 144 } },
  { islandId: 'new_providence', offset: { x: 51, y: 144 } },
  { islandId: 'new_providence', offset: { x: 190, y: 72 } },
  { islandId: 'new_providence', offset: { x: 274, y: 142 } },
  { islandId: 'new_providence', offset: { x: -269, y: 148 } },
  { islandId: 'new_providence', offset: { x: -109, y: 148 } },
  { islandId: 'new_providence', offset: { x: -29, y: 214 } },
  { islandId: 'new_providence', offset: { x: 110, y: 142 } },
  { islandId: 'new_providence', offset: { x: 131, y: 214 } },
  { islandId: 'new_providence', offset: { x: 211, y: 214 } },
  { islandId: 'new_providence', offset: { x: 350, y: 142 } },
  { islandId: 'new_providence', offset: { x: -297, y: 132 } }, // was outside the island polygon; refixed 2026-08-04
  { islandId: 'new_providence', offset: { x: -189, y: 218 } },
  { islandId: 'new_providence', offset: { x: -109, y: 218 } },
  { islandId: 'new_providence', offset: { x: 30, y: 212 } },
  { islandId: 'new_providence', offset: { x: 51, y: 284 } },
  { islandId: 'new_providence', offset: { x: 131, y: 284 } },
  { islandId: 'new_providence', offset: { x: 291, y: 218 } },
  { islandId: 'new_providence', offset: { x: -54, y: 307 } }, // was outside the island polygon; refixed 2026-08-04
  { islandId: 'new_providence', offset: { x: -109, y: 288 } },
  { islandId: 'new_providence', offset: { x: -29, y: 288 } },
  { islandId: 'new_providence', offset: { x: 108, y: 305 } },
  { islandId: 'new_providence', offset: { x: 190, y: 282 } },
  { islandId: 'new_providence', offset: { x: 214, y: 84 } }, // was outside the island polygon; refixed 2026-08-04
];

export function housesForIsland(islandId: string): House[] {
  return HOUSES.filter((h) => h.islandId === islandId);
}

export function houseWorldPosition(
  house: House,
  islandPosition: { x: number; y: number }
): { x: number; y: number } {
  return { x: islandPosition.x + house.offset.x, y: islandPosition.y + house.offset.y };
}
