/** Purely visual row-house scenery: fills out the residential district around the town core
 * so it reads as a dense, real settlement instead of a handful of named buildings on grass.
 * No interior, no interaction, no per-tick proximity checks — just a footprint on the map,
 * like background buildings in GTA. Positions were procedurally generated and filtered to land
 * + clearance from every other marker before being pasted in here.
 *
 * Full-town rebuild 2026-08-07 (item 52) — "start again," per direct feedback with reference
 * images of real 17th-century outlaw ports (Port Royal, Tortuga) and several hand-drawn fantasy
 * harbor-town maps: "organic, non-linear... waterfront centric... narrow thoroughfares... tightly
 * packed buildings," not a formal grid. Every prior iteration (see the item 39-50 history this
 * comment used to hold) kept the same fundamental shape — a hub-and-spoke square with row houses
 * lining a handful of streets — and kept failing the same feedback in different ways. This pass
 * replaced the shape instead: Tortuga's north coast is now a real horseshoe bay (see islands.ts),
 * and housing is a dense, organically-jittered scatter (not a grid, not row-lined spokes) packed
 * into the band between the coastal high street and the buildings behind it, all the way around
 * the crescent — 95 houses, generated by Poisson-disc-style rejection sampling (min 21 units
 * apart, min ~42 units from any building) and verified with a TypeScript script run directly
 * against the live data: every point inside TORTUGA_SHAPE, clear of every building/landmark/
 * marker, clear of every other house. The rural 'path' trails (West Point Shack, the Ruins, La
 * Ringot Fields, etc.) stay deliberately house-free — the same handful of standalone homesteads
 * near those as before covers the "sporadic elsewhere" half of the original ask, unchanged. */
export interface House {
  islandId: string;
  offset: { x: number; y: number }; // relative to island center, in world units
}

export const HOUSES: House[] = [
  // Dense organic house scatter wrapping the horseshoe bay, west headland to east headland —
  // Poisson-disc-style sampling rather than row-lined streets (95 houses).
  { islandId: 'tortuga_cove', offset: { x: -170, y: -218 } },
  { islandId: 'tortuga_cove', offset: { x: 144, y: -202 } },
  { islandId: 'tortuga_cove', offset: { x: -54, y: -199 } },
  { islandId: 'tortuga_cove', offset: { x: -135, y: -45 } },
  { islandId: 'tortuga_cove', offset: { x: -205, y: -128 } },
  { islandId: 'tortuga_cove', offset: { x: 285, y: -110 } },
  { islandId: 'tortuga_cove', offset: { x: 248, y: -251 } },
  { islandId: 'tortuga_cove', offset: { x: 168, y: -205 } },
  { islandId: 'tortuga_cove', offset: { x: 311, y: -87 } },
  { islandId: 'tortuga_cove', offset: { x: 17, y: -200 } },
  { islandId: 'tortuga_cove', offset: { x: -137, y: -71 } },
  { islandId: 'tortuga_cove', offset: { x: -163, y: -58 } },
  { islandId: 'tortuga_cove', offset: { x: 353, y: -192 } },
  { islandId: 'tortuga_cove', offset: { x: -191, y: -241 } },
  { islandId: 'tortuga_cove', offset: { x: -53, y: -26 } },
  { islandId: 'tortuga_cove', offset: { x: 104, y: -172 } },
  { islandId: 'tortuga_cove', offset: { x: -24, y: -187 } },
  { islandId: 'tortuga_cove', offset: { x: -156, y: -262 } },
  { islandId: 'tortuga_cove', offset: { x: 117, y: -25 } },
  { islandId: 'tortuga_cove', offset: { x: 154, y: -44 } },
  { islandId: 'tortuga_cove', offset: { x: -105, y: -60 } },
  { islandId: 'tortuga_cove', offset: { x: 251, y: -76 } },
  { islandId: 'tortuga_cove', offset: { x: -88, y: -48 } },
  { islandId: 'tortuga_cove', offset: { x: -168, y: -93 } },
  { islandId: 'tortuga_cove', offset: { x: 356, y: -149 } },
  { islandId: 'tortuga_cove', offset: { x: 195, y: -218 } },
  { islandId: 'tortuga_cove', offset: { x: 325, y: -123 } },
  { islandId: 'tortuga_cove', offset: { x: 69, y: -179 } },
  { islandId: 'tortuga_cove', offset: { x: -85, y: -148 } },
  { islandId: 'tortuga_cove', offset: { x: -175, y: -289 } },
  { islandId: 'tortuga_cove', offset: { x: 226, y: -268 } },
  { islandId: 'tortuga_cove', offset: { x: 219, y: -87 } },
  { islandId: 'tortuga_cove', offset: { x: -238, y: -152 } },
  { islandId: 'tortuga_cove', offset: { x: -256, y: -111 } },
  { islandId: 'tortuga_cove', offset: { x: 186, y: -246 } },
  { islandId: 'tortuga_cove', offset: { x: 206, y: -34 } },
  { islandId: 'tortuga_cove', offset: { x: 9, y: -176 } },
  { islandId: 'tortuga_cove', offset: { x: -268, y: -132 } },
  { islandId: 'tortuga_cove', offset: { x: -35, y: -214 } },
  { islandId: 'tortuga_cove', offset: { x: 222, y: -170 } },
  { islandId: 'tortuga_cove', offset: { x: 292, y: -76 } },
  { islandId: 'tortuga_cove', offset: { x: 215, y: -246 } },
  { islandId: 'tortuga_cove', offset: { x: 177, y: -59 } },
  { islandId: 'tortuga_cove', offset: { x: 328, y: -149 } },
  { islandId: 'tortuga_cove', offset: { x: 88, y: -190 } },
  { islandId: 'tortuga_cove', offset: { x: 129, y: -59 } },
  { islandId: 'tortuga_cove', offset: { x: 271, y: -56 } },
  { islandId: 'tortuga_cove', offset: { x: -109, y: -257 } },
  { islandId: 'tortuga_cove', offset: { x: -108, y: -223 } },
  { islandId: 'tortuga_cove', offset: { x: -93, y: -22 } },
  { islandId: 'tortuga_cove', offset: { x: -83, y: -239 } },
  { islandId: 'tortuga_cove', offset: { x: -60, y: -131 } },
  { islandId: 'tortuga_cove', offset: { x: 237, y: -193 } },
  { islandId: 'tortuga_cove', offset: { x: 153, y: -226 } },
  { islandId: 'tortuga_cove', offset: { x: -143, y: -289 } },
  { islandId: 'tortuga_cove', offset: { x: -289, y: -217 } },
  { islandId: 'tortuga_cove', offset: { x: 376, y: -141 } },
  { islandId: 'tortuga_cove', offset: { x: -229, y: -104 } },
  { islandId: 'tortuga_cove', offset: { x: 34, y: -169 } },
  { islandId: 'tortuga_cove', offset: { x: 242, y: -110 } },
  { islandId: 'tortuga_cove', offset: { x: 92, y: -131 } },
  { islandId: 'tortuga_cove', offset: { x: 140, y: -143 } },
  { islandId: 'tortuga_cove', offset: { x: -150, y: -197 } },
  { islandId: 'tortuga_cove', offset: { x: -122, y: -24 } },
  { islandId: 'tortuga_cove', offset: { x: 39, y: -191 } },
  { islandId: 'tortuga_cove', offset: { x: 229, y: -66 } },
  { islandId: 'tortuga_cove', offset: { x: -207, y: -102 } },
  { islandId: 'tortuga_cove', offset: { x: -46, y: -61 } },
  { islandId: 'tortuga_cove', offset: { x: -68, y: -62 } },
  { islandId: 'tortuga_cove', offset: { x: -134, y: -254 } },
  { islandId: 'tortuga_cove', offset: { x: 197, y: -169 } },
  { islandId: 'tortuga_cove', offset: { x: 104, y: -209 } },
  { islandId: 'tortuga_cove', offset: { x: 227, y: -38 } },
  { islandId: 'tortuga_cove', offset: { x: -187, y: -60 } },
  { islandId: 'tortuga_cove', offset: { x: -70, y: -215 } },
  { islandId: 'tortuga_cove', offset: { x: -141, y: -95 } },
  { islandId: 'tortuga_cove', offset: { x: -237, y: -128 } },
  { islandId: 'tortuga_cove', offset: { x: 96, y: -42 } },
  { islandId: 'tortuga_cove', offset: { x: -171, y: -119 } },
  { islandId: 'tortuga_cove', offset: { x: 208, y: -64 } },
  { islandId: 'tortuga_cove', offset: { x: 332, y: -101 } },
  { islandId: 'tortuga_cove', offset: { x: 115, y: -137 } },
  { islandId: 'tortuga_cove', offset: { x: 125, y: -214 } },
  { islandId: 'tortuga_cove', offset: { x: 364, y: -169 } },
  { islandId: 'tortuga_cove', offset: { x: 254, y: -42 } },
  { islandId: 'tortuga_cove', offset: { x: -202, y: -79 } },
  { islandId: 'tortuga_cove', offset: { x: 339, y: -167 } },
  { islandId: 'tortuga_cove', offset: { x: 269, y: -90 } },
  { islandId: 'tortuga_cove', offset: { x: -12, y: -170 } },
  { islandId: 'tortuga_cove', offset: { x: 183, y: -34 } },
  { islandId: 'tortuga_cove', offset: { x: -239, y: -301 } },
  { islandId: 'tortuga_cove', offset: { x: 122, y: -189 } },
  { islandId: 'tortuga_cove', offset: { x: 165, y: -23 } },
  { islandId: 'tortuga_cove', offset: { x: 251, y: -212 } },
  { islandId: 'tortuga_cove', offset: { x: -126, y: -275 } },
  // Sporadic houses: a single standalone homestead near each outlying location that's still on a
  // rural trail rather than a real street, instead of a second neighborhood — matches the existing
  // outpost pattern (West Point Shack, the Ruins, etc).
  { islandId: 'tortuga_cove', offset: { x: -368, y: 58 } }, // near West Point Shack
  { islandId: 'tortuga_cove', offset: { x: -478, y: 14 } }, // near El Fuerte Viejo (the Ruins)
  { islandId: 'tortuga_cove', offset: { x: 372, y: 168 } }, // near the Trapper's Camp
  { islandId: 'tortuga_cove', offset: { x: 224, y: 350 } }, // near the Old Landing Dock
  { islandId: 'tortuga_cove', offset: { x: 320, y: 220 } }, // near La Ringot Fields
  { islandId: 'tortuga_cove', offset: { x: 476, y: -40 } }, // near the High Woods
  { islandId: 'tortuga_cove', offset: { x: -110, y: 416 } }, // near the Forgotten Graves

  // Detached Row ("add everything" pass, 2026-08-13): nine houses evenly spaced along a straight
  // street south of the packed harbor core, per Blueprint Sheet 3 — a later, tidier addition to
  // the town rather than more of the cramped waterfront. Sits on the one long clear east-west
  // stretch of open ground between Bois Sombre and the coastline, checked clear of every existing
  // offset. See streets.ts for the row's own street plus its connector back to the harbor.
  { islandId: 'tortuga_cove', offset: { x: -260, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: -192, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: -124, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: -56, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: 12, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: 80, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: 148, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: 216, y: 300 } },
  { islandId: 'tortuga_cove', offset: { x: 284, y: 300 } },

  // New Providence residential grid: generated the same way as Tortuga's original grid — candidate positions
  // along a residential avenue grid, filtered to inside the real island polygon and clear of
  // every building/fort/quest marker and every other house (see GAME_DESIGN.md for the script).
  { islandId: 'new_providence', offset: { x: -269, y: -278 } },
  // (-120,-104) dropped — too close to the rum resource node at (-140,-100), missed in the
  // original generation pass because resource nodes weren't in that script's marker list.
  { islandId: 'new_providence', offset: { x: -189, y: -278 } },
  { islandId: 'new_providence', offset: { x: -189, y: -202 } },
  { islandId: 'new_providence', offset: { x: -109, y: -278 } },
  { islandId: 'new_providence', offset: { x: -109, y: -202 } },
  { islandId: 'new_providence', offset: { x: -29, y: -278 } },
  { islandId: 'new_providence', offset: { x: -29, y: -202 } },
  { islandId: 'new_providence', offset: { x: 51, y: -278 } },
  { islandId: 'new_providence', offset: { x: 51, y: -202 } },
  { islandId: 'new_providence', offset: { x: 131, y: -278 } },
  { islandId: 'new_providence', offset: { x: 131, y: -202 } },
  { islandId: 'new_providence', offset: { x: -349, y: -132 } },
  { islandId: 'new_providence', offset: { x: -269, y: -132 } },
  { islandId: 'new_providence', offset: { x: -189, y: -132 } },
  { islandId: 'new_providence', offset: { x: -109, y: -132 } },
  { islandId: 'new_providence', offset: { x: -29, y: -132 } },
  { islandId: 'new_providence', offset: { x: 51, y: -132 } },
  { islandId: 'new_providence', offset: { x: 211, y: -132 } },
  { islandId: 'new_providence', offset: { x: -290, y: -72 } },
  { islandId: 'new_providence', offset: { x: -210, y: -68 } },
  { islandId: 'new_providence', offset: { x: -130, y: -68 } },
  { islandId: 'new_providence', offset: { x: -50, y: -68 } },
  { islandId: 'new_providence', offset: { x: 116, y: -63 } },
  { islandId: 'new_providence', offset: { x: 190, y: -68 } },
  { islandId: 'new_providence', offset: { x: 270, y: -68 } },
  { islandId: 'new_providence', offset: { x: 350, y: -68 } },
  { islandId: 'new_providence', offset: { x: -349, y: 8 } },
  { islandId: 'new_providence', offset: { x: -269, y: 8 } },
  { islandId: 'new_providence', offset: { x: -189, y: 8 } },
  { islandId: 'new_providence', offset: { x: -109, y: 8 } },
  { islandId: 'new_providence', offset: { x: 51, y: 74 } },
  { islandId: 'new_providence', offset: { x: 190, y: 2 } },
  { islandId: 'new_providence', offset: { x: 270, y: 2 } },
  { islandId: 'new_providence', offset: { x: 350, y: 2 } },
  { islandId: 'new_providence', offset: { x: -349, y: 78 } },
  { islandId: 'new_providence', offset: { x: -269, y: 78 } },
  { islandId: 'new_providence', offset: { x: -50, y: 72 } },
  { islandId: 'new_providence', offset: { x: -29, y: 144 } },
  { islandId: 'new_providence', offset: { x: 51, y: 144 } },
  { islandId: 'new_providence', offset: { x: 190, y: 72 } },
  { islandId: 'new_providence', offset: { x: 274, y: 142 } },
  { islandId: 'new_providence', offset: { x: -269, y: 148 } },
  { islandId: 'new_providence', offset: { x: -109, y: 148 } },
  { islandId: 'new_providence', offset: { x: -29, y: 214 } },
  { islandId: 'new_providence', offset: { x: 110, y: 142 } },
  { islandId: 'new_providence', offset: { x: 131, y: 214 } },
  { islandId: 'new_providence', offset: { x: 211, y: 214 } },
  { islandId: 'new_providence', offset: { x: 350, y: 142 } },
  { islandId: 'new_providence', offset: { x: -297, y: 132 } }, // was outside the island polygon; refixed 2026-08-04
  { islandId: 'new_providence', offset: { x: -189, y: 218 } },
  { islandId: 'new_providence', offset: { x: -109, y: 218 } },
  { islandId: 'new_providence', offset: { x: 30, y: 212 } },
  { islandId: 'new_providence', offset: { x: 51, y: 284 } },
  { islandId: 'new_providence', offset: { x: 131, y: 284 } },
  { islandId: 'new_providence', offset: { x: 291, y: 218 } },
  { islandId: 'new_providence', offset: { x: -54, y: 307 } }, // was outside the island polygon; refixed 2026-08-04
  { islandId: 'new_providence', offset: { x: -109, y: 288 } },
  { islandId: 'new_providence', offset: { x: -29, y: 288 } },
  { islandId: 'new_providence', offset: { x: 108, y: 305 } },
  { islandId: 'new_providence', offset: { x: 190, y: 282 } },
  { islandId: 'new_providence', offset: { x: 214, y: 84 } }, // was outside the island polygon; refixed 2026-08-04
];

export function housesForIsland(islandId: string): House[] {
  return HOUSES.filter((h) => h.islandId === islandId);
}

export function houseWorldPosition(
  house: House,
  islandPosition: { x: number; y: number }
): { x: number; y: number } {
  return { x: islandPosition.x + house.offset.x, y: islandPosition.y + house.offset.y };
}
