/** Pure decoration: fills out open land with visual density (a real forest, scattered ruin
 * rubble, overgrown graves) with zero gameplay hook — no proximity toast, no collision, no
 * interaction of any kind. Landmarks are for the one or two named, described points of interest
 * in an area; Scenery is for the dozens of small background details around them, the same way
 * Houses are background buildings with no per-item identity.
 *
 * Coordinates below were generated by a script that scattered candidate points inside each zone
 * and filtered them to real Tortuga land, clear of every building/house/landmark/resource node,
 * and clear of each other — see GAME_DESIGN.md for the approach. */
export interface SceneryProp {
  islandId: string;
  offset: { x: number; y: number }; // relative to island center, in world units
  emoji: string;
  fontSize?: number; // default 22
}

export const SCENERY: SceneryProp[] = [
  // The High Woods (east cape): a real scattered forest around the landmark and its two timber
  // stands, mixing pine/hardwood inland with palms toward the shoreline.
  { islandId: 'tortuga_cove', offset: { x: 332, y: -102 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 414, y: -94 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 348, y: 100 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 540, y: 82 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 520, y: 118 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 408, y: 24 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 452, y: 60 }, emoji: '🌳', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 390, y: -16 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 390, y: -146 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 338, y: -162 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 358, y: -64 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 462, y: 128 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 516, y: -40 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 472, y: 8 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 488, y: 90 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 366, y: 54 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 476, y: -68 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 372, y: -104 }, emoji: '🌳', fontSize: 22 },
  // Thickened 2026-08-02 (2026-08-02 world-doubling left the original 18 trees looking sparse —
  // doubling every coordinate quadruples the ground each tree "covers," so restoring the same
  // canopy density needs roughly 4x the count, not 2x) — script-generated the same way as above.
  { islandId: 'tortuga_cove', offset: { x: 500, y: 144 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 424, y: 124 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 382, y: 14 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 529, y: 50 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 311, y: -20 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 446, y: 4 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 481, y: 34 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 317, y: 110 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 372, y: 139 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 310, y: 82 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 325, y: -62 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 445, y: -84 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 292, y: -182 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 442, y: 35 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 418, y: -62 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 487, y: -24 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 515, y: 92 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 342, y: 137 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 292, y: -144 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 294, y: -75 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 418, y: 48 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 369, y: -32 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 310, y: 140 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 321, y: -134 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 404, y: 145 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 450, y: 98 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 369, y: -179 }, emoji: '🌴', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 524, y: -12 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 380, y: 88 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 338, y: 72 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 556, y: 4 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 344, y: -22 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 354, y: 23 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 385, y: -53 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 487, y: 118 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 495, y: 60 }, emoji: '🌴', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 291, y: 34 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 436, y: -109 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 296, y: -114 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 403, y: -119 }, emoji: '🌳', fontSize: 28 },
  { islandId: 'tortuga_cove', offset: { x: 420, y: -2 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 396, y: 63 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 314, y: 55 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 545, y: 29 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 350, y: -129 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 291, y: 121 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 427, y: 73 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 499, y: 1 }, emoji: '🌴', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 462, y: -36 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 390, y: -80 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 363, y: -152 }, emoji: '🌴', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 323, y: -184 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 382, y: 114 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 365, y: -6 }, emoji: '🌳', fontSize: 24 },

  // El Fuerte Viejo (west cape): broken masonry and overgrowth scattered around the ruin itself,
  // so it reads as an actual collapsed fortification from outside, not just one marker icon.
  { islandId: 'tortuga_cove', offset: { x: -570, y: -16 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -472, y: 34 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -562, y: 14 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -470, y: -54 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -523, y: 39 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -546, y: -25 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -494, y: -48 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -470, y: -11 }, emoji: '🪨', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -523, y: -46 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -537, y: 14 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -502, y: 26 }, emoji: '🪨', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -484, y: 9 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -460, y: 11 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -548, y: 36 }, emoji: '🪨', fontSize: 16 },

  // Abandoned quarter (south coast): scorched ground, creeping moss, and old grave markers
  // around the ruins of the old landing and its burying ground.
  { islandId: 'tortuga_cove', offset: { x: 28, y: 398 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 12, y: 440 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -120, y: 440 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -32, y: 382 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 68, y: 384 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 60, y: 424 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -130, y: 400 }, emoji: '🪨', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -3, y: 415 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 88, y: 419 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 102, y: 376 }, emoji: '🪦', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 40, y: 374 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 2, y: 376 }, emoji: '🪨', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -159, y: 387 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -84, y: 389 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 135, y: 377 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -30, y: 407 }, emoji: '🪦', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: 131, y: 438 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 155, y: 411 }, emoji: '🪨', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -155, y: 435 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -53, y: 395 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -114, y: 371 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -34, y: 444 }, emoji: '🪦', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -99, y: 408 }, emoji: '🌿', fontSize: 18 },
];

export function sceneryForIsland(islandId: string): SceneryProp[] {
  return SCENERY.filter((s) => s.islandId === islandId);
}

export function sceneryWorldPosition(
  prop: SceneryProp,
  islandPosition: { x: number; y: number }
): { x: number; y: number } {
  return { x: islandPosition.x + prop.offset.x, y: islandPosition.y + prop.offset.y };
}
