/** Pure decoration: fills out open land with visual density (a real forest, scattered ruin
 * rubble, overgrown graves) with zero gameplay hook — no proximity toast, no collision, no
 * interaction of any kind. Landmarks are for the one or two named, described points of interest
 * in an area; Scenery is for the dozens of small background details around them, the same way
 * Houses are background buildings with no per-item identity.
 *
 * Coordinates below were generated by a script that scattered candidate points inside each zone
 * and filtered them to real Tortuga land, clear of every building/house/landmark/resource node,
 * and clear of each other — see GAME_DESIGN.md for the approach. */
export interface SceneryProp {
  islandId: string;
  offset: { x: number; y: number }; // relative to island center, in world units
  emoji: string;
  fontSize?: number; // default 22
}

export const SCENERY: SceneryProp[] = [
  // The High Woods (east cape): a real scattered forest around the landmark and its two timber
  // stands, mixing pine/hardwood inland with palms toward the shoreline.
  { islandId: 'tortuga_cove', offset: { x: 166, y: -51 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 207, y: -47 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 174, y: 50 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 270, y: 41 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 260, y: 59 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 204, y: 12 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 226, y: 30 }, emoji: '🌳', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 195, y: -8 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 195, y: -73 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 169, y: -81 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 179, y: -32 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 231, y: 64 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 258, y: -20 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 236, y: 4 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 244, y: 45 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 183, y: 27 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 238, y: -34 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 186, y: -52 }, emoji: '🌳', fontSize: 22 },

  // El Fuerte Viejo (west cape): broken masonry and overgrowth scattered around the ruin itself,
  // so it reads as an actual collapsed fortification from outside, not just one marker icon.
  { islandId: 'tortuga_cove', offset: { x: -285, y: -8 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -236, y: 17 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -281, y: 7 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -235, y: -27 }, emoji: '🪨', fontSize: 20 },

  // Abandoned quarter (south coast): scorched ground, creeping moss, and old grave markers
  // around the ruins of the old landing and its burying ground.
  { islandId: 'tortuga_cove', offset: { x: 14, y: 199 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 6, y: 220 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -60, y: 220 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -16, y: 191 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 34, y: 192 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 30, y: 212 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -65, y: 200 }, emoji: '🪨', fontSize: 16 },
];

export function sceneryForIsland(islandId: string): SceneryProp[] {
  return SCENERY.filter((s) => s.islandId === islandId);
}

export function sceneryWorldPosition(
  prop: SceneryProp,
  islandPosition: { x: number; y: number }
): { x: number; y: number } {
  return { x: islandPosition.x + prop.offset.x, y: islandPosition.y + prop.offset.y };
}
