/** Pure decoration: fills out open land with visual density (a real forest, scattered ruin
 * rubble, overgrown graves) with zero gameplay hook — no proximity toast, no collision, no
 * interaction of any kind. Landmarks are for the one or two named, described points of interest
 * in an area; Scenery is for the dozens of small background details around them, the same way
 * Houses are background buildings with no per-item identity.
 *
 * Coordinates below were generated by a script that scattered candidate points inside each zone
 * and filtered them to real Tortuga land, clear of every building/house/landmark/resource node,
 * and clear of each other — see GAME_DESIGN.md for the approach. */
export interface SceneryProp {
  islandId: string;
  offset: { x: number; y: number }; // relative to island center, in world units
  emoji: string;
  fontSize?: number; // default 22
}

export const SCENERY: SceneryProp[] = [
  // The High Woods (east cape): a real scattered forest around the landmark and its two timber
  // stands, mixing pine/hardwood inland with palms toward the shoreline.
  { islandId: 'tortuga_cove', offset: { x: 332, y: -102 }, emoji: '🌳', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 414, y: -94 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 348, y: 100 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 540, y: 82 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 520, y: 118 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 408, y: 24 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 452, y: 60 }, emoji: '🌳', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 390, y: -16 }, emoji: '🌲', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 390, y: -146 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 338, y: -162 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 358, y: -64 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 462, y: 128 }, emoji: '🌴', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 516, y: -40 }, emoji: '🌴', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 472, y: 8 }, emoji: '🌲', fontSize: 24 },
  { islandId: 'tortuga_cove', offset: { x: 488, y: 90 }, emoji: '🌳', fontSize: 22 },
  { islandId: 'tortuga_cove', offset: { x: 366, y: 54 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 476, y: -68 }, emoji: '🌲', fontSize: 26 },
  { islandId: 'tortuga_cove', offset: { x: 372, y: -104 }, emoji: '🌳', fontSize: 22 },

  // El Fuerte Viejo (west cape): broken masonry and overgrowth scattered around the ruin itself,
  // so it reads as an actual collapsed fortification from outside, not just one marker icon.
  { islandId: 'tortuga_cove', offset: { x: -570, y: -16 }, emoji: '🪨', fontSize: 20 },
  { islandId: 'tortuga_cove', offset: { x: -472, y: 34 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -562, y: 14 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -470, y: -54 }, emoji: '🪨', fontSize: 20 },

  // Abandoned quarter (south coast): scorched ground, creeping moss, and old grave markers
  // around the ruins of the old landing and its burying ground.
  { islandId: 'tortuga_cove', offset: { x: 28, y: 398 }, emoji: '🌿', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 12, y: 440 }, emoji: '🪨', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: -120, y: 440 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -32, y: 382 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 68, y: 384 }, emoji: '🪦', fontSize: 18 },
  { islandId: 'tortuga_cove', offset: { x: 60, y: 424 }, emoji: '🌿', fontSize: 16 },
  { islandId: 'tortuga_cove', offset: { x: -130, y: 400 }, emoji: '🪨', fontSize: 16 },
];

export function sceneryForIsland(islandId: string): SceneryProp[] {
  return SCENERY.filter((s) => s.islandId === islandId);
}

export function sceneryWorldPosition(
  prop: SceneryProp,
  islandPosition: { x: number; y: number }
): { x: number; y: number } {
  return { x: islandPosition.x + prop.offset.x, y: islandPosition.y + prop.offset.y };
}
